import test from 'node:test';import assert from 'node:assert/strict';import {validate,toCSV} from './lib/validation.js';import responses from './api/responses.js';import exportHandler from './api/export.js';
const sample=()=>({id:'b596a8d9-d49c-45a8-9fce-559104776c34',surveyVersion:'1.0',consent:true,elapsedMs:20000,overall:'Example feedback',answers:[0,1,2].map(i=>({test:i+1,order:['A','B'],preference:'Same',ratings:{A:{ease:4,clarity:4},B:{ease:4,clarity:4}},reasons:[],comment:'',trials:Object.fromEntries(['A','B'].map(v=>[v,{elapsedMs:1000,outcome:i===0?'Approved':i===1?'Submitted':{status:'In progress',team:'Electrical team',time:'Today, 17:00'}}]))}))});
const res=()=>({code:0,body:null,setHeader(){},status(n){this.code=n;return this},json(d){this.body=d;return this},send(d){this.body=d},end(){}});
test('Complete survey accepted, missing consent and ratings rejected',()=>{assert.equal(validate(sample()),true);const d=sample();d.consent=false;assert.equal(validate(d),false);d.consent=true;d.answers[0].ratings.B.ease=9;assert.equal(validate(d),false);assert.equal(validate({}),false);});
test('CSV has three test rows, escapes quotes and spreadsheet formulas',()=>{const d=sample();d.overall='=HYPERLINK("bad")';const csv=toCSV([d]);assert.equal(csv.split('\r\n').length,4);assert.match(csv,/'=HYPERLINK/);assert.match(csv,/""bad""/);});
test('Missing storage never reports a saved response',async()=>{delete process.env.BLOB_READ_WRITE_TOKEN;delete process.env.BLOB_STORE_ID;const r=res();await responses({method:'POST',headers:{'content-type':'application/json'},body:sample()},r);assert.equal(r.code,503);assert.equal(r.body.saved,undefined);});
test('Public requests cannot export responses',async()=>{const r=res();await exportHandler({method:'GET',headers:{}},r);assert.equal(r.code,401);});
import {JSDOM} from 'jsdom';import {readFile} from 'node:fs/promises';
test('All six practice flows, feedback validation, save failure and retry',async()=>{const dom=new JSDOM(await readFile('public/index.html','utf8'),{url:'http://localhost:3000',runScripts:'outside-only'});const w=dom.window;w.HTMLElement.prototype.scrollIntoView=function(){};let sent,success=false;w.fetch=async(url,opts)=>{if(url.includes('health'))return {json:async()=>({ready:false})};sent=JSON.parse(opts.body);return {ok:success,json:async()=>success?{saved:true}:{error:'Test save failure'}};};w.eval(await readFile('public/app.js','utf8'));const q=s=>w.document.querySelector(s);assert.equal(w.document.querySelectorAll('.phone').length,6);q('#consent').checked=true;
for(const v of ['A','B']){q(`#screen-0-${v} [data-decision="Approved"]`).click();const screen=q(`#screen-1-${v}`);screen.querySelector('[name=location]').value='B-block common corridor';screen.querySelector('[name=category]').value='Plumbing';screen.querySelector('[name=description]').value='Water leaks outside Flat B-204.';screen.querySelector('form').dispatchEvent(new w.Event('submit',{cancelable:true}));const track=q(`#screen-2-${v}`);track.querySelector('[name=status]').value='In progress';track.querySelector('[name=team]').value='Electrical team';track.querySelector('[name=time]').value='Today, 17:00';track.querySelector('form').dispatchEvent(new w.Event('submit',{cancelable:true}));}
assert.equal(w.document.querySelectorAll('.tried.done').length,6);for(let i=0;i<3;i++){q(`[name="${i}-preference"][value="Same"]`).checked=true;for(const v of ['A','B'])for(const kind of ['ease','clarity'])q(`[name="${i}-${v}-${kind}"][value="4"]`).checked=true;}
q('#submit').click();await new Promise(r=>setTimeout(r,10));assert.equal(validate(sent),true);assert.match(q('#submit-status').textContent,/Test save failure/);assert.equal(q('#submit').disabled,false);success=true;q('#submit').click();await new Promise(r=>setTimeout(r,10));assert.match(q('.finish').textContent,/feedback is saved/);dom.window.close();});
